### ISSUE TITLE
Some lower bounds unnecessarily restrictive?

### ISSUE THREAD

**Issue by gibiansky** [jeffreyrosenbluth/static-canvas#1]
I tried to compile this but had some issues, due to some lower bounds. I changed `free` to be `>= 4.9` and `mtl` to be `>= 2.1`, and it installed and compiled fine. Do these lower bounds exist for a reason and/or could they be removed?

**Comment by jeffreyrosenbluth** [comment]
I think they could be widened. I'll look into it and push a new version to hackage as soon as i can.

**Comment by jeffreyrosenbluth** [comment]
Fixed in version 0.2
