### ISSUE TITLE
Can only have one canvas per page?

### ISSUE THREAD

**Issue by gibiansky** [jeffreyrosenbluth/static-canvas#2]
Hey,

I tried making an IHaskellDisplay instance for static-canvas (see [here](http://www.reddit.com/r/haskell/comments/2vr60u/building_an_ihaskell_display_for_staticcanvas/)) but found that if I had two canvases rendered using `buildScript` in the same HTML page, then the first one would just be modified by the commands in the second one.

This seems like a bug? Sadly `static-canvas` (which is awesome!) is not really useable with IHaskell until that's fixed...

Perhaps add a `buildCanvasUniq` function that works by storing a global counter in IO (with just an unsafe global MVar) that increments the counter every time it makes a new canvas. This is a bit ugly but works. Or allow `buildScript` to take a name, and offload that unsafe ugliness to IHaskell and other users :)

**Comment by jeffreyrosenbluth** [comment]
Thanks, I'll work on it.

**Comment by jeffreyrosenbluth** [comment]
Checkout the `buildScript'` function in 0.2. Let me know if this is what you need to make an IHaskellDisplay. 

btw. thanks for the kind words on reddit and in your blob post
